server:
  port: 8080

spring:
  application:
    name: odoo-gateway
  
  profiles:
    active: dev
    
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: odoo-dev
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        namespace: odoo-dev
        group: DEFAULT_GROUP
        file-extension: yml
        username: nacos
        password: nacos
        
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 认证服务路由
        - id: auth-service
          uri: lb://odoo-auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0
            
        # 用户服务路由
        - id: user-service
          uri: lb://odoo-user
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=0
            - name: AuthFilter
              
        # CRM服务路由
        - id: crm-service
          uri: lb://odoo-crm
          predicates:
            - Path=/api/v1/crm/**
          filters:
            - StripPrefix=0
            - name: AuthFilter
            
        # 库存服务路由
        - id: inventory-service
          uri: lb://odoo-inventory
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=0
            - name: AuthFilter
            
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5
          max-wait: 3000ms

# 日志配置
logging:
  level:
    com.odoo.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    health:
      show-details: always

# JWT配置
jwt:
  secret: odoo-java-secret-key-for-jwt-token-sign
  expiration: 7200
  refresh-expiration: 604800
  issuer: odoo-java

# 网关配置
gateway:
  # 排除认证的路径
  exclude-auth-paths:
    - /api/v1/auth/login
    - /api/v1/auth/register
    - /api/v1/auth/refresh
    - /actuator/**
    - /favicon.ico
  
  # 限流配置
  rate-limit:
    enabled: true
    default-capacity: 100
    default-tokens: 10 